name: Mule CloudHub 2.0 Deploy

on:
  push:
    branches:
      - main   
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build Mule App
      run: mvn clean package

    - name: Deploy to CloudHub 2.0
      run: mvn clean deploy -X -DmuleDeploy "-Danypoint.clientId=58e295be816e4999858a7ebf507b11ce" "-Danypoint.clientSecret=5f004Bd0F1F0445299f43b1Be34a6443" "-Danypoint.environment=Sandbox" -Danypoint.organizationId=001b9e0e-b33b-4b0b-a11d-1b175a5492f2           